services:
  aurum-api:
    build: ./backend
    container_name: aurum-api
    restart: unless-stopped
    ports:
      - "7870:7870"
    volumes:
      - ./backend:/app
      - ~/aurum_docker/aurum/scripts:/app/scripts
      - ~/aurum_docker/aurum/uploads:/app/uploads
      - ~/aurum_docker/aurum/outputs:/app/outputs
      - ~/aurum_docker/aurum/data:/app/data
    extra_hosts:
      - "host.docker.internal:host-gateway"

  aurum-frontend:
    image: node:22
    container_name: aurum-frontend
    restart: unless-stopped
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    command: bash -lc "npm install && npm run dev"
    depends_on:
      - aurum-api
